language: node_js
node_js:
  - "stable"

install:
  - cd demo
  - npm install

before_deploy:
  - git add -f node_modules/

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: chmccc/FlacheQL
  bucket: flacheql
  region: us-west-1
- provider: codedeploy
  skip_cleanup: true
  revision_type: github
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: flacheql
  key: latest.zip
  bundle_type: zip
  application: FlacheQL
  deployment_group: FlacheQL
  region: us-west-1
  on: *2

script:
  - zip -r latest * >/dev/null
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip